import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton, Manrope} from "next/font/google";
import "./globals.css";
import "./styles.css";
import styles from "./layout.module.css";
import Header from "@/components/Header/Header";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});
const manrope = Manrope({
  weight:"700",
  subsets: ["latin"],
  variable: "--font-manrope",
  
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} antialiased`}
      >
        <div className={styles.page}>
          <Header />
          <main className={styles.mainContent}>{children}</main>
          <footer className="h-[50px] bg-black text-white flex items-center justify-center">
            <p>Copyright © 2025 - Les Petits Plats</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
